var municipios_arr = [
	{"id": "1", "municipio": "Ahualulco"},
	{"id": "2", "municipio": "Alaquines"},
	{"id": "3", "municipio": "Aquismón"},
	{"id": "4", "municipio": "Armadillo de los Infantes"},
	{"id": "5", "municipio": "Cárdenas"},
	{"id": "6", "municipio": "Catorce"},
	{"id": "7", "municipio": "Cedral"},
	{"id": "8", "municipio": "Cerritos"},
	{"id": "9", "municipio": "Cerro de San Pedro"},
	{"id": "10", "municipio": "Ciudad del Maíz"},
	{"id": "11", "municipio": "Ciudad Fernández"},
	{"id": "12", "municipio": "Tancanhuitz"},
	{"id": "13", "municipio": "Ciudad Valles"},
	{"id": "14", "municipio": "Coxcatlán"},
	{"id": "15", "municipio": "Charcas"},
	{"id": "16", "municipio": "Ebano"},
	{"id": "17", "municipio": "Guadalcázar"},
	{"id": "18", "municipio": "Huehuetlán"},
	{"id": "19", "municipio": "Lagunillas"},
	{"id": "20", "municipio": "Matehuala"},
	{"id": "21", "municipio": "Mexquitic de Carmona"},
	{"id": "22", "municipio": "Moctezuma"},
	{"id": "23", "municipio": "Rayón"},
	{"id": "24", "municipio": "Rioverde"},
	{"id": "25", "municipio": "Salinas"},
	{"id": "26", "municipio": "San Antonio"},
	{"id": "27", "municipio": "San Ciro de Acosta"},
	{"id": "28", "municipio": "San Luis Potosí"},
	{"id": "29", "municipio": "San Martín Chalchicuahutla"},
	{"id": "30", "municipio": "San Nicolás Tolentino"},
	{"id": "31", "municipio": "Santa Catarina"},
	{"id": "32", "municipio": "Santa María del Río"},
	{"id": "33", "municipio": "Santo Domingo"},
	{"id": "34", "municipio": "San Vicente Tancuayalab"},
	{"id": "35", "municipio": "Soledad de Gracaino Sánchez"},
	{"id": "36", "municipio": "Tamasopo"},
	{"id": "37", "municipio": "Tamazunchale"},
	{"id": "38", "municipio": "Tampacán"},
	{"id": "39", "municipio": "Tampamolón Corona"},
	{"id": "40", "municipio": "Tamuín"},
	{"id": "41", "municipio": "Tanlajás"},
	{"id": "42", "municipio": "Tanquián de Escobedo"},
	{"id": "43", "municipio": "Tierra Nueva"},
	{"id": "44", "municipio": "Vanegas"},
	{"id": "45", "municipio": "Venado"},
	{"id": "46", "municipio": "Villa de Arriaga"},
	{"id": "47", "municipio": "Villa de Guadalupe"},
	{"id": "48", "municipio": "Villa de la Paz"},
	{"id": "49", "municipio": "Villa de Ramos"},
	{"id": "50", "municipio": "Villa de Reyes"},
	{"id": "51", "municipio": "Villa Hidalgo"},
	{"id": "52", "municipio": "Villa Juárez"},
	{"id": "53", "municipio": "Axtla de Terrazas"},
	{"id": "54", "municipio": "Xilitla"},
	{"id": "55", "municipio": "Zaragoza"},
	{"id": "56", "municipio": "Villa de Arista"},
	{"id": "57", "municipio": "Matlapa"},
	{"id": "58", "municipio": "El Naranjo"}
];
